package lakshmi;// Generated by Selenium IDE
import core.engine.AsquaredWebDriverFactory;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class TestNavigationExport {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    //driver = new ChromeDriver();
    driver = AsquaredWebDriverFactory.getDriver("chrome");
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void hw1() {
    driver.get("http://newtours.demoaut.com/");
    assertThat(driver.getTitle(), is("Welcome: Mercury Tours"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(1) > td > p:nth-child(1) > img"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("td:nth-child(2) > table > tbody > tr > td > img"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("SIGN-ON"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("REGISTER"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("SUPPORT"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("CONTACT"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > td > table > tbody > tr:nth-child(2) font")).getText(), is("User Name:"));
    driver.findElement(By.name("userName")).click();
    {
      List<WebElement> elements = driver.findElements(By.name("userName"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("body > div")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > td > table > tbody > tr:nth-child(3) font")).getText(), is("Password:"));
    {
      List<WebElement> elements = driver.findElements(By.name("password"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.name("login"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("body > div")).click();
    {
      List<WebElement> elements = driver.findElements(By.linkText("Destinations"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("Vacations"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("REGISTER"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) tr:nth-child(1) > td > font")).getText(), is("Atlanta to Las Vegas"));
  }
}
