package asquared;// Generated by Selenium IDE

import core.engine.AsquaredWebDriverFactory;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class TestLoginTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        //driver = new ChromeDriver();
        driver = AsquaredWebDriverFactory.getDriver("chrome");
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testLogin() {
        driver.get("http://www.newtours.demoaut.com/");
        assertThat(driver.getTitle(), is("Welcome: Mercury Tours"));
        {
            List<WebElement> elements = driver.findElements(By.name("userName"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.name("userName")).sendKeys("asquared");
        {
            List<WebElement> elements = driver.findElements(By.name("password"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.name("password")).sendKeys("asquared");
        {
            List<WebElement> elements = driver.findElements(By.name("login"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.name("login")).click();
        assertThat(driver.getTitle(), is("Find a Flight: Mercury Tours:"));
    }
}
