package rushna;// Generated by Selenium IDE
import core.engine.AsquaredWebDriverFactory;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class TestNavigationExport {
  private WebDriver driver; // variable  physical chrome browser (computer)
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before //annotations open the browser!!!!
  public void setUp() { // method
    //driver = new ChromeDriver();
    driver = AsquaredWebDriverFactory.getDriver("chrome");
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>(); //instantiation  of variables
  }
  @After //annotations close
  public void tearDown() {
    driver.quit();
  }
  @Test //annotations
  public void mercurytours() {
    driver.get("http://newtours.demoaut.com/");
    driver.findElement(By.linkText("SIGN-ON")).click();
    assertThat(driver.getTitle(), is("Sign-on: Mercury Tours"));
    driver.findElement(By.linkText("SUPPORT")).click();
    assertThat(driver.getTitle(), is("Under Construction: Mercury Tours"));
    driver.findElement(By.linkText("CONTACT")).click();
    assertThat(driver.getTitle(), is("Under Construction: Mercury Tours"));
    driver.findElement(By.linkText("Home")).click();
    assertThat(driver.getTitle(), is("Welcome: Mercury Tours"));
    driver.findElement(By.linkText("Flights")).click();
    assertThat(driver.getTitle(), is("Welcome: Mercury Tours"));
    driver.findElement(By.linkText("Hotels")).click();
    assertThat(driver.getTitle(), is("Under Construction: Mercury Tours"));
    driver.findElement(By.linkText("Car Rentals")).click();
    assertThat(driver.getTitle(), is("Under Construction: Mercury Tours"));
    driver.findElement(By.linkText("Cruises")).click();
    assertThat(driver.getTitle(), is("Cruises: Mercury Tours"));
    driver.findElement(By.linkText("Destinations")).click();
    assertThat(driver.getTitle(), is("Under Construction: Mercury Tours"));
    driver.findElement(By.linkText("Vacations")).click();
    assertThat(driver.getTitle(), is("Under Construction: Mercury Tours"));
  }
}
